<a href="https://colab.research.google.com/github/vishInAi/Data-Analysis-Py/blob/main/Notebooks/IntroNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY

- Library used to work with Arrays
- functions for working domain of lin algebra, fouries transform, matrices.
- Open Source
- Widely used in Data Science and Scientific-Computing

### Key Features

#### 1. N-Dimensional Arrays:

- Provides powerful n-dimensional array object, ndarray.
- Arrays Faster, More Compact than Py lists.
- Supports Math Operations.

In [12]:
import numpy as np

In [13]:
# Creating a 1d array
a1 = np.array([1,2,3,4])
print(f"The 1D Array : {a1}")

# Creating a 2d array
a2 = np.array([[1,2],[3,4],[5,6]])
print(f"The 2D Array : \n {a2}")

The 1D Array : [1 2 3 4]
The 2D Array : 
 [[1 2]
 [3 4]
 [5 6]]


#### 2. Broadcasting:

- Allows arithmetic operations on arrays of different shapes
- Simplifies code and improves performance

In [14]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
c = a+b
print(f"The addition of two arrays of Different Dimentions 1d and 2d : {c}")

The addition of two arrays of Different Dimentions 1d and 2d : [[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 3. Vectorized Operations:

- Perform element-wise op without explicit loops.
- Enhances Performance and Readability

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a*b
print(f"Product of two 1D arrays containing 3D Vectors : \n {c}")

Product of two 1D arrays containing 3D Vectors : 
 [ 4 10 18]


#### 4. Indexing and Slicing:

- Access and modify array elements using indices and slices.
- Supports advanced indexing techniques.

In [16]:
arr = np.array([10,20,30,40,50])
print(f"lets slice the array from the 2nd element upto 5th and print {arr[1:4]}") # Slicing
arr[2] = 100 # Modifying an element
print(f"Lets look at the modified array {arr}")

lets slice the array from the 2nd element upto 5th and print [20 30 40]
Lets look at the modified array [ 10  20 100  40  50]


#### 5. Linear Algebra:

- Functions for matrix operations, eigenvalues, and more.
- Useful for scientific and engineering applications.

In [17]:
matrix = np.array([[1,2],[3,4]])
determinant = np.linalg.det(matrix)
print(f"The array matrix : {determinant}")

The array matrix : -2.0000000000000004


#### Advantages of NumPy

##### 1. Performance:

- Numpy arays are most efficient than Python lists in terms of speed and memory usage.
- Operations on arrays are implemented in C, making them very fast.

##### 2. Convenience:

- Provides wide range of Math functions.
- Simplifies complex mathematical computations.

##### 3. Interoperability:

- Compatible with other lib like SciPy, Pandas, Matplotlib.
- Facilitates data exchange between different libraries.

#### Disadvantages of NumPy

##### 1. Learning Curve:

- Requires some time to learn and understand.
- Syntax and concepts might be challenged for beginners.

##### 2. Memory Consumption:

- Large arrays can consume significant memory.
- Not suitable for small-scale applications where Python lists suffice

#### Uses of NumPy

##### 1. Data Analysis:

- Efficiently handle and process large datasets.
- Commonly used in data science and Machine Learning.

##### 2. Scientific Computing:

- Perform complex mathematical and Statistical Operations.
- Widely used in Research and Engineering.

#### Summary

NumPy is a versatile and powefil library that enhances Python's capabilities for Numerical Computations.
Efficient Array Operations, Broadcasting and Math functions make it a go to tool for data scientists and engineers.