In [2]:
import numpy as np

In [3]:
da = np.array([3, 5, 7, 9, 12])

In [4]:
type(da)

numpy.ndarray

In [5]:
da.max()

np.int64(12)

In [6]:
da.min()

np.int64(3)

In [7]:
da.mean()

np.float64(7.2)

In [8]:
da.sum()

np.int64(36)

In [9]:
np.median(da)

np.float64(7.0)

In [10]:
da = np.array(1977)
print(da)

1977


In [11]:
a = np.array([[2, 4, 2, 8],[2, 3, 1, 8]], float)

In [12]:
np.corrcoef(a)

array([[1.        , 0.98552746],
       [0.98552746, 1.        ]])

In [13]:
x = np.array([2,4,2,8])

In [14]:
y = np.array([2,3,1,8])

In [15]:
np.corrcoef([x,y])

array([[1.        , 0.98552746],
       [0.98552746, 1.        ]])

In [16]:
r = np.corrcoef(x,y)
print(r)

[[1.         0.98552746]
 [0.98552746 1.        ]]


In [17]:
r[0,1]

np.float64(0.9855274566525744)

In [18]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [19]:
import scipy.stats
scipy.stats.pearsonr(x,y)

PearsonRResult(statistic=np.float64(0.9855274566525747), pvalue=np.float64(0.014472543347425315))

In [20]:
da = np.array([[22,15,33], [24,25,16], [17,44,88]])
da

array([[22, 15, 33],
       [24, 25, 16],
       [17, 44, 88]])

In [21]:
da.shape
print('shape of array', da.shape)

shape of array (3, 3)


In [22]:
np.linspace (0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.logspace(0,1,10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [24]:
from numpy import random

rn = random.randint(100)

print(rn)

19


In [25]:
da = np.array([[[1,3,5],[2,4,6]],[[1,3,5],[2,4,6]]])
da

array([[[1, 3, 5],
        [2, 4, 6]],

       [[1, 3, 5],
        [2, 4, 6]]])

In [26]:
da = np.array([1,2,3,4])

print(da.dtype)

int64


In [27]:
rn = random.rand(3)

print(rn)

[0.87355052 0.2019381  0.13318959]


In [28]:
da + 1

array([2, 3, 4, 5])

In [29]:
da * da

array([ 1,  4,  9, 16])

In [30]:
da

array([1, 2, 3, 4])

In [31]:
a = np.arange(20).reshape(4,5)

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
x = np.array([12,np.nan,31,56,88,np.nan])
x

array([12., nan, 31., 56., 88., nan])

In [35]:
x

array([12., nan, 31., 56., 88., nan])